export const dictionary = {
    'alt_logo': 'Logo do Nosso Lar. Traços de uma casa com nosso lar escrito ao meio.',
    'text_home': 'Organize as atividades do seu lar entre todos os membros da família e crie recompensas para quem conseguir mais pontos',
    'label_create_list': 'criar lista',
    'label_has_list': 'já tenho uma lista',
    'alt_close_btn': 'fechar pop up',
    'label_created_list': 'Lista criada com sucesso!',
    'label_link': 'Link',
    'label_copy': 'Copiar',
    'label_go_list': 'Ir para lista',
    'label_access_link': 'Insira aqui seu link de acesso',
    'label_invalid_link': 'link inválido',
    'label_tutorial': 'Assista ao tutorial:',
    'label_list_name_placeholder': 'Nome da lista...',
    'label_add_task': 'Adicionar tarefa',
    'label_success_change_name': 'Nome alterado com sucesso!',
    'label_edit_task': 'Salvar tarefa',
    'label_adult': 'Adulto',
    'label_child': 'Infantil',
    'label_task': 'Tarefa',
    'label_how_to_do_it': 'Como fazer?',
    'label_responsable': 'Responsáveis',
    'label_add_person': 'Adicionar pessoa',
    'label_recurrent_task': 'Tarefa recorrente',
    'label_desc_recurrent': 'Esta tarefa irá ser renovada automaticamente.',
    'label_question_recurrent': 'Renovar a tarefa a cada quantos dias?',
    'label_recurrency': 'Recorrência',
    'label_success_add_task': 'Tarefa adicionada com sucesso!',
    'label_success_edit_task': 'Tarefa alterada com sucesso!',
    'label_success_delete_task': 'Tarefa excluída com sucesso',
    'label_error': 'Ocorreu um erro nesta operação. Tente novamente mais tarde',
    'label_delete_task': 'Excluir tarefa',
    'label_delete_list': 'Exluir lista',
    'label_settings': 'Ajustes',
    'label_people': 'Pessoas',
    'label_reward': 'Recompensa',
    'label_people_desc': 'Estas são as pessoas da sua lista.',
    'label_reward_desc': 'Defina uma recompensa para o momento em que todas as tarefas forem concluídas.',
    'label_save_reward': 'Salvar recompensa',
    'label_reward_placeholder': 'Ex.: Ir à praia no próximo final de semana.',
    'label_alt_avatar': 'Avatar de ',
    'label_alt_star': 'Símbolo de estrela',
    'label_success_reward': 'Recompensa salva com sucesso!',
    'label_success_delete_list': 'Lista excluída com sucesso',
    'label_edit_person': 'Salvar pessoa',
    'label_delete_person': 'Excluir pessoa',
    'label_person_name': 'Nome da pessoa',
    'label_alt_avatar_type': 'Avatar do tipo ',
    'label_avatar_definition': 'Selecione o avatar',
    'label_success_edit_person': 'Pessoa salva com sucesso!',
    'label_success_add_person': 'Pessoa criada com sucesso!',
    'label_success_delete_person': 'Pessoa excluída com sucesso',
    'label_person_error': 'Adicione um nome e um avatar',
    'label_success_copy': 'Link copiado com sucesso!',
    'label_error_add_task': 'Adicione um tipo de tarefa e um responsável',
    'label_define_task_name': 'Defina um nome para a tarefa',
    'label_task_name': 'Nome da tarefa',
    'label_see_people': 'Pessoas e pontuação',
    'alt_logo_list': 'Ícone de uma lista',
    'alt_logo_list': 'Ícone de configurações',
    'alt_back-btn': 'Ícone seta para a esquerda para voltar para tela anterior',
    'alt_expand_btn': 'Ícone seta para baixo para expandir o campo',
    'alt_logo_people': 'Ícone de pessoas com estrelas',
    'alt_logo_reward': 'Ícone de recompensa. Representa um trofeu.'
}